# Numpy Tutorial
- Indexing 과 broadcasting 복습

## Array indexing
* Numpy array의 indexing은 일반적인 list와 유사하다. 
* 단, indexing해서 분리한 array도 원래 array의 memory를 참조하기 때문에 변경할 때 유의하여야 한다.

In [56]:
import numpy as np

In [57]:
np.__version__

'1.20.1'

In [58]:
a = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]
)

In [59]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [60]:
type(a)

numpy.ndarray

In [61]:
a.shape

(3, 4)

In [62]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [66]:
a[0]

array([1, 2, 3, 4])

In [68]:
b = a[0:2]

In [69]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [72]:
b[0, 0] = 100
print(b)

[[100   2   3   4]
 [  5   6   7   8]]


In [73]:
print(a)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [74]:
from copy import deepcopy

In [76]:
c = deepcopy(b)
print(c)

[[100   2   3   4]
 [  5   6   7   8]]


In [78]:
c[0, 0] = 200
print(c)

[[200   2   3   4]
 [  5   6   7   8]]


In [79]:
print(b)

[[100   2   3   4]
 [  5   6   7   8]]


In [1]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, '\n')

# [[2 3]
#  [6 7]]
# call-by-reference가 된 경우
b = a[:2, 1:3]
print(b)

print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[2 3]
 [6 7]]
2
77


In [83]:
## 실습
# (H, W, C)
a = np.random.randn(4, 5, 3)
print(a.shape)

(4, 5, 3)


In [85]:
b = a[:, :, 0:1]
print(b.shape)

(4, 5, 1)


####  Slicing을 할 때는 dimension이 낮아질 수 있다.
- Slicing을 하는 방법에는 여러가지가 있는데, integer를 활용해 indexing을 할 때는 dimension이 낮아지고, slicing을 이용해 indexing 할 때는 dimension이 유지된다.

In [86]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, a.shape)

row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a

print("___________________________")
print("Slicing Row")
print("___________________________")

print(row_r1, row_r1.shape, '\n')
print(row_r2, row_r2.shape, '\n')
print(row_r3, row_r3.shape, '\n')


col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print("___________________________")
print("Slicing Column")
print("___________________________")
print(col_r1, col_r1.shape, '\n')
print(col_r2, col_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
___________________________
Slicing Row
___________________________
[5 6 7 8] (4,) 

[[5 6 7 8]] (1, 4) 

[[5 6 7 8]] (1, 4) 

___________________________
Slicing Column
___________________________
[ 2  6 10] (3,) 

[[ 2]
 [ 6]
 [10]] (3, 1)


In [4]:
## 실습

- 슬라이싱을 만들 때 주의해야 할 점은 슬라이싱 된 배열은 원본 배열과 같은 데이터를 참조하기 때문에 슬라이싱 된 배열을 수정하면 원본 배열 역시 수정됨

In [5]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
c = a[1:3, 2:3]
print(c)
c[0] = 10
print(c)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[6]
 [9]]
[[10]
 [ 9]]
[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]
 [10 11 12]]


In [6]:
## 실습

#### Integer array를 이용해 indexing을 할 수 있다. 
- Slicing을 할 때는 네모난 subarray만 추출할 수 있지만, integer array를 이용할 경우 임의의 수치들을 꺼내올 수 있다.

In [92]:
a = np.array([
    [1,2], 
    [3,4], 
    [5,6]
])
print(a)
print(a.shape)
## [1, 4, 5]를 만들 수 있는 방법 두 가지 

## Solution 1
print("Solution 1 : ", np.array([a[0, 0], a[1, 1], a[2, 0]]))

## Solution 2
print("Solution 2 : ", a[[0, 1, 2], [0, 1, 0]])

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
Solution 1 :  [1 4 5]
Solution 2 :  [1 4 5]


In [8]:
## 실습

In [95]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

## TO DO 

# Select one element from each row of a using the indices
b = np.array([0, 2, 0, 1])

# Prints "[ 1 6 7 11]"
print(a[np.arange(4), b])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]


In [10]:
## 실습

- Boolean array로도 indexing을 할 수 있다. 

In [99]:
mask = a > 5
print(mask)

[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]


In [101]:
b = a[mask]
print(a)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 6  7  8  9 10 11 12]


In [102]:
a[mask] = 0
print(a)

[[1 2 3]
 [4 5 0]
 [0 0 0]
 [0 0 0]]


In [103]:
a = np.random.randn(2, 2)
print(a)

[[-0.64662588  0.07274908]
 [ 0.32312858  0.58273996]]


In [105]:
a[a < 0] = 0
print(a)

[[0.         0.07274908]
 [0.32312858 0.58273996]]


In [11]:
print(a > 2)
print(a[a > 2])

[[False False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[ 3  4  5  6  7  8  9 10 11 12]


In [12]:
## 실습

## Broadcasting
- Broadcasting is strong!
- Broadcasting은 우리가 잘아는 방송과 관련된 뜻이고 유사한 의미로, broadcast란 단어는 무언가를 '흩뿌리고 퍼뜨리고 전파'할 때 사용하는 단어이다. 아래 실습을 해보면서 전파한다는 의미를 더 설명해보도록 하겠다.

## Two tensors are “broadcastable” if the following rules hold:

- 1. Each tensor has at least one dimension.
- 2. When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exis

In [114]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [118]:
b = np.array([[10, 20, 30]])
print(b)
print(b.shape)

[[10 20 30]]
(1, 3)


In [119]:
c = a + b
print(c)

[[11 22 33]
 [14 25 36]]


In [122]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10, 11, 12]
])
v = np.array([1, 0, 1])
y = np.empty_like(x)   

## first solution
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [124]:
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [128]:
## Second Solution
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10, 11, 12]
])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
y = x + vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [134]:
## Third Solution
v = np.array([1, 0, 1])
print(v.shape)
v = np.expand_dims(v, axis=0)
print(v.shape)
vv = np.repeat(v, repeats=4, axis=0)  # Stack 4 copies of v on top of each other
print(vv.shape)
y = x + vv  
print(y)

(3,)
(1, 3)
(4, 3)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [136]:
## Fourth Solution - Broad Casting
print(x.shape)
print(v.shape)
y = x + v  # Add v to each row of x using broadcasting
print(y)

(4, 3)
(1, 3)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [13]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   

## first solution
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

## Second Solution
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
y = x + vv  
print(y)

## Third Solution
v = np.array([1, 0, 1])
v = np.expand_dims(v, axis=0)
vv = np.repeat(v, repeats=4, axis=0)  # Stack 4 copies of v on top of each other
y = x + vv  
print(y)

## Fourth Solution - Broad Casting
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [14]:
## 실습

In [138]:
## Broadcasting possible cases
def checkbroadcasting(x, y):
    try:
        x+y
        return True
    except:
        return False


x=np.empty((0))
y=np.empty((2,2))
print("problem 1 : ", checkbroadcasting(x,y))

x=np.empty((2))
y=np.empty((2,2))
print("problem 2 : ", checkbroadcasting(x,y))
 
x=np.empty((5,3,4,1))
y=np.empty((3,4,1))
print("problem 3 : ", checkbroadcasting(x,y))

x=np.empty((5,3,4,1))
y=np.empty((3,1,1))
print("problem 4 : ", checkbroadcasting(x,y))

x=np.empty((5,2,4,1))
y=np.empty((3,1,1))
print("problem 5 : ", checkbroadcasting(x,y))

problem 1 :  False
problem 2 :  True
problem 3 :  True
problem 4 :  True
problem 5 :  False


In [140]:
x=np.empty((0))
print(x.shape)
y=np.empty((2,2))
print(y.shape)
print("problem 1 : ", checkbroadcasting(x,y))

(0,)
(2, 2)
problem 1 :  False


In [144]:
x=np.array([1, 2])
print(x.shape)
y=np.array([[1, 2], [3, 4]])
print(y.shape)
print("problem 2 : ", checkbroadcasting(x,y))
print(x + y)

(2,)
(2, 2)
problem 2 :  True
[[2 4]
 [4 6]]


In [145]:
x=np.empty((5,3,4,1))
y=np.empty((3,4,1))
print("problem 3 : ", checkbroadcasting(x,y))

problem 3 :  True


In [146]:
x=np.empty((5,3,4,1))
y=np.empty((3,1,1))
print("problem 4 : ", checkbroadcasting(x,y))

problem 4 :  True


In [155]:
x=np.empty((5,3,3,1))
y=np.empty((3,4))
print("problem 5 : ", checkbroadcasting(x,y))

problem 5 :  True


In [148]:
x=np.empty((5,2,4,1))
y=np.empty((1))
print("problem 6 : ", checkbroadcasting(x,y))

problem 6 :  True


In [16]:
## 실습

## 지금까지 배운 Numpy에서의 indexing 과 Broadcasting 방법이 모두 Pytorch에도 적용 된다.

## 그럼 왜 PyTorch를 사용하는가?

# Pytorch Tutorial

## Tensors
* Tensorflow의 Tensor와 다르지 않다.
  * Numpy의 ndarrays를 기본적으로 활용하고 있다.
  * Numpy의 ndarrays의 대부분의 operation을 사용할 수 있도록 구성되어 있다.
* Numpy의 operation은 CPU만을 이용해 느리지만 Tensor는 CUDA를 활용해 GPU를 이용하기 때문에 빠르게 연산을 진행할 수 있다.


In [156]:
%matplotlib inline
import torch

In [159]:
x = torch.Tensor(5, 3)
print(x, '\n')
print(x.shape)
print(x.size())

tensor([[-7.5739e+04,  4.5849e-41, -7.5739e+04],
        [ 4.5849e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.4013e-45],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  1.4013e-45]]) 

torch.Size([5, 3])
torch.Size([5, 3])


In [160]:
# Construct a matrix with the list
x = torch.tensor([[3, 4, 5], [1, 2, 3]])
print(x, '\n')
print(x.shape)

tensor([[3, 4, 5],
        [1, 2, 3]]) 

torch.Size([2, 3])


In [162]:
# Construct a randomly initialized matrix 
x = torch.rand(5, 3) # np.random.rand
print(x, '\n')
print(x.grad)

tensor([[0.9723, 0.6899, 0.0356],
        [0.6539, 0.2133, 0.7549],
        [0.5915, 0.6877, 0.6221],
        [0.6352, 0.4728, 0.5338],
        [0.4593, 0.0836, 0.8070]]) 

None


In [18]:
# Construct a 5 x 3 matrix, uninitialized (random initialized)
x = torch.Tensor(5, 3)
print(x, '\n')

# Construct a randomly initialized matrix 
x = torch.rand(5, 3)
print(x, '\n')

# Construct a matrix with the list
x = torch.tensor([[3, 4, 5], [1, 2, 3]])
print(x, '\n')

# Get its size
print(x.size())
print(x.shape)

# Get its grad
print(x.grad)

tensor([[-7.5739e+04,  4.5849e-41, -5.7093e-13],
        [ 3.0785e-41,  6.6741e+22,  4.3953e-11],
        [ 1.7254e+19,  5.0284e-14,  1.1704e-19],
        [ 1.3563e-19,  2.9503e-39,  4.5849e-41],
        [-1.0803e+05,  4.5849e-41,  2.7045e-43]]) 

tensor([[0.0020, 0.7242, 0.1427],
        [0.7630, 0.9375, 0.8915],
        [0.5187, 0.9806, 0.6207],
        [0.2121, 0.3891, 0.6553],
        [0.9884, 0.2705, 0.8285]]) 

tensor([[3, 4, 5],
        [1, 2, 3]]) 

torch.Size([2, 3])
torch.Size([2, 3])
None


In [19]:
## 실습

### dtype and device 
 * dtype - Tensor의 데이터 타입
 * device - Tensor의 작업 위치 (cpu or cuda)

In [165]:
x = torch.tensor([[3, 4, 5], [1, 2, 3]], dtype=torch.float64)
print(x, '\n')

y = torch.tensor([[3, 4, 5], [1, 2, 3]], dtype=torch.int)
print(y, '\n')


print(x + y)

tensor([[3., 4., 5.],
        [1., 2., 3.]], dtype=torch.float64) 

tensor([[3, 4, 5],
        [1, 2, 3]], dtype=torch.int32) 

tensor([[ 6.,  8., 10.],
        [ 2.,  4.,  6.]], dtype=torch.float64)


In [21]:
## 실습

In [168]:
x = torch.tensor([[3, 4, 5], [1, 2, 3]], dtype=torch.float32)
print(x, '\n')
print(x.dtype)
y = x.double()
print(y)

tensor([[3., 4., 5.],
        [1., 2., 3.]]) 

torch.float32
tensor([[3., 4., 5.],
        [1., 2., 3.]], dtype=torch.float64)


In [22]:
y = y.double() 
print(y, '\n')

print(x + y)

tensor([[3., 4., 5.],
        [1., 2., 3.]], dtype=torch.float64) 

tensor([[ 6.,  8., 10.],
        [ 2.,  4.,  6.]], dtype=torch.float64)


In [23]:
## 실습

In [170]:
x = torch.tensor([[3, 4, 5], [1, 2, 3]], dtype=torch.float32)
print(x.device)
x = x.to(torch.device('cuda'))
print(x.device)

cpu
cuda:0


In [171]:
print(torch.cuda.is_available())

True


In [173]:
device = torch.device('cuda') # 'cpu'
x = x.to(device)
print(x, '\n')
print(x.device, '\n')

device = torch.device('cuda:1')
x = x.to(device)

print(x, '\n')
print(x.device, '\n')

tensor([[3., 4., 5.],
        [1., 2., 3.]], device='cuda:0') 

cuda:0 

tensor([[3., 4., 5.],
        [1., 2., 3.]], device='cuda:1') 

cuda:1 



In [175]:
print(x.device)
x = x.to(torch.device('cpu'))
print(x.device)

cuda:1
cpu


In [176]:
print(x.device)

cpu


In [182]:
x = x.cuda()
print(x.device)
x = x.cpu()
print(x.device)

cuda:0
cpu


In [25]:
## 실습

In [185]:
device_0 = torch.device('cuda:0')
device_1 = torch.device('cuda:1')

x = torch.randn(4, 3, dtype=torch.float64)
y = torch.randn(4, 3, dtype=torch.float32)
z = torch.randint(0, 10, (4, 3), dtype=torch.int32)

z = z.to(device_1)

print('Before "to" method')

print(x.dtype, x.device)
print(y.dtype, y.device)
print(z.dtype, z.device, '\n')


print('After "to" method')
# to method with specific dtype and device 
x = x.to(dtype=torch.int32, device=device_0)

# to method with some tensor 
y = y.to(z)
z = z.to(device='cpu')

print(x.dtype, x.device)
print(y.dtype, y.device)
print(z.dtype, z.device, '\n')

Before "to" method
torch.float64 cpu
torch.float32 cpu
torch.int32 cuda:1 

After "to" method
torch.int32 cuda:0
torch.int32 cuda:1
torch.int32 cpu 



In [27]:
## 실습

### Constructing like Numpy

In [186]:
x = torch.empty(3, 5)
print(x, '\n')

tensor([[0.0000e+00, 0.0000e+00, 1.4013e-45, 1.2612e-44, 1.4013e-45],
        [9.8091e-45, 1.1210e-44, 1.2612e-44, 4.2039e-45, 5.6052e-45],
        [8.4078e-45, 1.1210e-44, 8.9683e-44, 0.0000e+00, 1.5835e-43]]) 



In [189]:
x = torch.zeros(3, 5)
print(x, '\n')

x = torch.ones(3, 5)
print(x, '\n')

x = torch.full((3, 5), 3.1415)
print(x, '\n')

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) 

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

tensor([[3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415, 3.1415]]) 



In [191]:
x = torch.arange(0, 5, 1)
print(x, '\n')

tensor([0, 1, 2, 3, 4]) 



In [192]:
y = torch.linspace(0, 5, 9)
print(y, '\n')

tensor([0.0000, 0.6250, 1.2500, 1.8750, 2.5000, 3.1250, 3.7500, 4.3750, 5.0000]) 



In [193]:
z = torch.logspace(-10, 10, 5)
print(z, '\n')

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10]) 



In [194]:
z = torch.eye(5) # I: Identity Matrix
print(z, '\n')

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]) 



In [195]:
x = torch.empty(3, 5)
print(x, '\n')

x = torch.zeros(3, 5)
print(x, '\n')

x = torch.ones(3, 5)
print(x, '\n')

x = torch.full((3, 5), 3.1415)
print(x, '\n')

x = torch.arange(0, 5, 2)
print(x, '\n')

y = torch.linspace(0, 5, 9)
print(y, '\n')

z = torch.logspace(-10, 10, 5)
print(z, '\n')

z = torch.eye(5)
print(z, '\n')

# Construct a 3 x 5 matrix with random value from uniform distribution, i.e. Uniform[0, 1)
x = torch.rand(3, 5)

# Construct a 3 x 5 matrix with random value from normal distribution, i.e. Normal(0, 1)
x = torch.randn(3, 5)


x = torch.randint(3, 10, (3, 5))
print(x, '\n')

tensor([[-7.5739e+04,  4.5849e-41,  9.0966e-23,  3.0787e-41,  1.4013e-45],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  9.0937e-23,  3.0787e-41, -2.0974e-13]]) 

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) 

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

tensor([[3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415, 3.1415]]) 

tensor([0, 2, 4]) 

tensor([0.0000, 0.6250, 1.2500, 1.8750, 2.5000, 3.1250, 3.7500, 4.3750, 5.0000]) 

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10]) 

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]) 

tensor([[8, 3, 9, 3, 7],
        [6, 8, 5, 8, 7],
        [8, 5, 9, 4, 5]]) 



In [29]:
## 실습

### \*\_like function and new\_\* function
 * \*\_like: Tensor를 input으로 받아, Tensor 모양의 matrix를 return.
 * new\_\*: Shape를 input으로 받아, Tensor와 같은 type과 device를 가지는 matrix를 return

In [204]:
x = torch.rand(3, 5)
x = x.cuda()
y = x.new_zeros(2, 3)
# y = torch.zeros_like(x)
print(y.shape)
print(y.device)
print(y)
print(x.device)
print(y.device)
# z = x + y

torch.Size([2, 3])
cuda:0
tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')
cuda:0
cuda:0


In [30]:
y = torch.zeros_like(x)
print(y, '\n')

# Make zero matrix with attribute of x
z = x.new_zeros(2, 3)
print(z, '\n')
print(x.dtype, x.device)
print(z.dtype, z.device,'\n')

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]) 

tensor([[0, 0, 0],
        [0, 0, 0]]) 

torch.int64 cpu
torch.int64 cpu 



In [31]:
## 실습

- From numpy to tensor

In [208]:
a = np.ones(5)
b = torch.from_numpy(a)
print(b.device)
c = b.numpy()
print(type(c))
print("\n",a,"\n",b,"\n",c)

cpu
<class 'numpy.ndarray'>

 [1. 1. 1. 1. 1.] 
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 
 [1. 1. 1. 1. 1.]


In [33]:
## 실습

### Operations
* Operations에도 여러가지 syntax가 있다.

In [215]:
x = torch.rand(5, 3)
y = torch.rand(1, 3)

In [217]:
hyundai = x + y
print(hyundai)

tensor([[1.3943, 1.7993, 1.6014],
        [1.4621, 1.6473, 0.8761],
        [1.2929, 1.2117, 1.3055],
        [1.2954, 1.2846, 0.8653],
        [0.7702, 1.7095, 1.1845]])


In [221]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(y)
# z = x + y
y.add_(x)
print(y)
# y.add_(x)
# print("solution 1 : ", x + y, '\n')
# print("solution 1 : ", torch.add(x, y), '\n')

# result = torch.Tensor(5, 3)
# torch.add(x, y, out=result)
# print("solution 3 : ", result, '\n')

tensor([[0.2698, 0.1173, 0.1252],
        [0.9326, 0.1908, 0.5700],
        [0.7868, 0.4511, 0.0069],
        [0.1050, 0.0431, 0.0550],
        [0.5286, 0.7321, 0.0831]])
tensor([[0.2708, 0.8525, 0.1572],
        [1.7038, 0.9540, 1.4408],
        [1.3457, 0.6580, 0.7785],
        [0.1549, 0.8289, 0.9555],
        [1.0819, 0.7779, 0.3125]])


In [209]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print("solution 1 : ", x + y, '\n')


print("solution 2 : ", torch.add(x, y), '\n')


result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print("solution 3 : ", result, '\n')

y.add_(x)
print("solution 4 : ", y, '\n')

solution 1 :  tensor([[1.3333, 0.5676, 0.5711],
        [0.6093, 0.6187, 1.2319],
        [1.3260, 0.3188, 0.8614],
        [1.2587, 0.2385, 1.4925],
        [0.0774, 1.2341, 1.2397]]) 

solution 2 :  tensor([[1.3333, 0.5676, 0.5711],
        [0.6093, 0.6187, 1.2319],
        [1.3260, 0.3188, 0.8614],
        [1.2587, 0.2385, 1.4925],
        [0.0774, 1.2341, 1.2397]]) 

solution 3 :  tensor([[1.3333, 0.5676, 0.5711],
        [0.6093, 0.6187, 1.2319],
        [1.3260, 0.3188, 0.8614],
        [1.2587, 0.2385, 1.4925],
        [0.0774, 1.2341, 1.2397]]) 

solution 4 :  tensor([[1.3333, 0.5676, 0.5711],
        [0.6093, 0.6187, 1.2319],
        [1.3260, 0.3188, 0.8614],
        [1.2587, 0.2385, 1.4925],
        [0.0774, 1.2341, 1.2397]]) 



In [35]:
## 실습

- Same indexing as numpy

In [223]:
# indexing 또한 비슷하게
print(x)
print(x[:, 1], '\n')
print(x>0.5)
print(x[x > 0.5])

tensor([[0.0010, 0.7352, 0.0320],
        [0.7713, 0.7631, 0.8707],
        [0.5590, 0.2069, 0.7716],
        [0.0499, 0.7859, 0.9005],
        [0.5534, 0.0459, 0.2294]])
tensor([0.7352, 0.7631, 0.2069, 0.7859, 0.0459]) 

tensor([[False,  True, False],
        [ True,  True,  True],
        [ True, False,  True],
        [False,  True,  True],
        [ True, False, False]])
tensor([0.7352, 0.7713, 0.7631, 0.8707, 0.5590, 0.7716, 0.7859, 0.9005, 0.5534])


In [37]:
## 실습

### reshape and view

In [234]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
print(x)
print(x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [239]:
del x
torch.cuda.empty_cache()

In [238]:
x = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(x.shape)
print(x)
y = x.view(3, 1, 3)
print(y[:, :, 0])

torch.Size([1, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1],
        [4],
        [7]])


In [235]:
x = torch.arange(0, 10)
print(x, '\n')

y = x.reshape(2, 5)
z = y.reshape(10,)
print(y, '\n')
print(z)

# y[0, 0] = 3
# print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]) 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [38]:
# Change the shape of tensor 
x = torch.arange(0, 10)
print(x, '\n')

y = x.view(2, 5)
print(y, '\n')

x = torch.arange(0, 30).view(5, 6)
print(x, '\n')
print(x.size(), '\n')

y = x.view(-1, 2, 5)
print(y, '\n')
print(y.size(), '\n')

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]) 

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]) 

torch.Size([5, 6]) 

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]]) 

torch.Size([3, 2, 5]) 



In [39]:
#

x = torch.arange(0, 10)
x = x.reshape(-1,2,5)
print(x)
print(x.shape)

tensor([[[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]])
torch.Size([1, 2, 5])


## Questions from the last section

### Q1. tensorflow: numpy to tf tensor
-  tf.convert_to_tensor() in tensorflow>=2.0

### Q2. view vs. reshape
- The only difference is that reshape might copy the input tensor.
- This is related to the contiguity of the input tensor.
- "view" function only works if and only if the input tensor is contiguous.

In [253]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
print(x)
print(x.is_contiguous())
z = x.view(3, 2)
print(z)
z2 = x.reshape(3, 2)
print(z2)

tensor([[1, 2, 3],
        [4, 5, 6]])
True
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [257]:
y = x.t()
print(y)
print(y.is_contiguous())
z = y.reshape(2, 3)
print(z)
z[0] = 10
print(y)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
False
tensor([[1, 4, 2],
        [5, 3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


### transpose and permute

In [260]:
x = torch.rand(1, 2, 3)
print(x)
y = torch.transpose(x, 0, 2)  ## dim0 dim1 바꾸고 싶을 때
print(y)
y = y.contiguous()
print(y.is_contiguous())
z = x.permute(2, 1, 0)  ## dim0 dim1 ~ dimn 바꾸고 싶을 때
print(z)
print(z.is_contiguous())

tensor([[[0.1039, 0.0572, 0.3595],
         [0.4991, 0.5807, 0.7730]]])
tensor([[[0.1039],
         [0.4991]],

        [[0.0572],
         [0.5807]],

        [[0.3595],
         [0.7730]]])
True
tensor([[[0.1039],
         [0.4991]],

        [[0.0572],
         [0.5807]],

        [[0.3595],
         [0.7730]]])
False


In [261]:
x = torch.rand(3, 4, 5)
print(x[0, :, :])
y = torch.transpose(x, 0, 1)
print(y[:, 0, :])

tensor([[0.7159, 0.9104, 0.3810, 0.4249, 0.6850],
        [0.6222, 0.9410, 0.8945, 0.7266, 0.7523],
        [0.2084, 0.6476, 0.4023, 0.8560, 0.1249],
        [0.5671, 0.9291, 0.4229, 0.6683, 0.2911]])
tensor([[0.7159, 0.9104, 0.3810, 0.4249, 0.6850],
        [0.6222, 0.9410, 0.8945, 0.7266, 0.7523],
        [0.2084, 0.6476, 0.4023, 0.8560, 0.1249],
        [0.5671, 0.9291, 0.4229, 0.6683, 0.2911]])


In [41]:
## 실습

### squeeze and unsqueeze

In [262]:
x = torch.rand(1, 1, 20, 128)
print(x.shape)
x = x.squeeze() # [1, 1, 20, 128] -> [20, 128]
print(x.shape)

torch.Size([1, 1, 20, 128])
torch.Size([20, 128])


In [263]:
x2 = torch.rand(1, 1, 20, 128)
print(x2.shape)
x2 = x2.squeeze(dim=1) # [1, 1, 20, 128] -> [1, 20, 128]
print(x2.shape)

torch.Size([1, 1, 20, 128])
torch.Size([1, 20, 128])


In [264]:
print(x.shape)
x3 = x.unsqueeze(0)
print(x3.shape)

torch.Size([20, 128])
torch.Size([1, 20, 128])


In [42]:
x = torch.rand(1, 1, 20, 128)
print(x.shape)
x = x.squeeze() # [1, 1, 20, 128] -> [20, 128]
print(x.shape)
x2 = torch.rand(1, 1, 20, 128)
print(x2.shape)
x2 = x2.squeeze(dim=1) # [1, 1, 20, 128] -> [1, 20, 128]
print(x2.shape)

x3 = x.unsqueeze(0)
print(x3.shape)

torch.Size([1, 1, 20, 128])
torch.Size([20, 128])
torch.Size([1, 1, 20, 128])
torch.Size([1, 20, 128])
torch.Size([1, 20, 128])


In [43]:
## 실습

### multiplication and concatenation

In [265]:
x = torch.ones(5, 3)+1
y = torch.ones(5, 3)+2
z = x * y
print(x)
print(y)
print(z)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


In [266]:
## matrix multiplication
## y = W.T * x + b
z= torch.matmul(x, y.t())
print(x.shape)
print(y.shape)
print(z, z.shape)

torch.Size([5, 3])
torch.Size([5, 3])
tensor([[18., 18., 18., 18., 18.],
        [18., 18., 18., 18., 18.],
        [18., 18., 18., 18., 18.],
        [18., 18., 18., 18., 18.],
        [18., 18., 18., 18., 18.]]) torch.Size([5, 5])


In [270]:
print(x)
print(y)
z = torch.cat([x, y], dim=1)
print(z)
print(x.shape)
print(y.shape)
print(z.shape)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[2., 2., 2., 3., 3., 3.],
        [2., 2., 2., 3., 3., 3.],
        [2., 2., 2., 3., 3., 3.],
        [2., 2., 2., 3., 3., 3.],
        [2., 2., 2., 3., 3., 3.]])
torch.Size([5, 3])
torch.Size([5, 3])
torch.Size([5, 6])


In [44]:
## element wise multiplication
x = torch.ones(5, 3)+1
y = torch.ones(5, 3)+2
z = x * y
print(x.shape, y.shape)
print(z, z.shape)

## matrix multiplication
z= torch.matmul(x, y.t())
print(z, z.shape)

## concat
x = x.unsqueeze(0)
y = y.unsqueeze(0)
print(x.shape, y.shape)
z = torch.cat([x, y], dim=0)
print(z.shape)

torch.Size([5, 3]) torch.Size([5, 3])
tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]) torch.Size([5, 3])
tensor([[18., 18., 18., 18., 18.],
        [18., 18., 18., 18., 18.],
        [18., 18., 18., 18., 18.],
        [18., 18., 18., 18., 18.],
        [18., 18., 18., 18., 18.]]) torch.Size([5, 5])
torch.Size([1, 5, 3]) torch.Size([1, 5, 3])
torch.Size([2, 5, 3])


In [45]:
## 실습

### 넘파이의 다양한 operation들이 토치에 같은 함수나 변형된 함수로 대부분 탑재 되어있음.

# \***********Numpy Practice Time\***********

## PyTorch의 Autograd: automatic differentiation
* Autograd package는 Tensors가 사용할 수 있는 모든 Operation의 Gradient를 자동으로 계산해준다.
* Tensor의 required_grad attribute를 이용해 gradient의 계산여부를 결정할 수 있다.
  * 계산이 완료된 이후에 .backward()를 호출하면 자동으로 gradient를 계산한다.
  * .grad attribute를 통해 마찬가지로 gradient에 접근할 수 있다. 
  * .grad_fn attribute를 통해 해당 Variable이 어떻게 생성되었는지 확인할 수 있다. 해당 값으로 해당 노드의 local gradient 구할 수 있게 됨.
  
  

In [285]:
# Create a variable
# x = torch.ones(2, 2)
x = torch.ones(2, 2, requires_grad=True)

print(x)
print(x.requires_grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [286]:
y = x + 2
z = y * y * 3
out = z.mean()

out.retain_grad()
z.retain_grad()
y.retain_grad()

# y,z는 operation으로 생성된 결과이기 때문에 grad_fn이 있지만 , x는 없다.
print(out.data, out.grad, out.grad_fn)
print(z.data, z.grad, z.grad_fn)
print(y.data, y.grad, y.grad_fn)
print(x.data, x.grad, x.grad_fn)


out.backward()

print('##############################')
print(out.data, out.grad)
print(z.data, z.grad)
print(y.data, y.grad)
print(x.data, x.grad)

tensor(27.) None <MeanBackward0 object at 0x7fcef03f1880>
tensor([[27., 27.],
        [27., 27.]]) None <MulBackward0 object at 0x7fcef03fbc40>
tensor([[3., 3.],
        [3., 3.]]) None <AddBackward0 object at 0x7fcef04573d0>
tensor([[1., 1.],
        [1., 1.]]) None None
##############################
tensor(27.) tensor(1.)
tensor([[27., 27.],
        [27., 27.]]) tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
tensor([[3., 3.],
        [3., 3.]]) tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([[1., 1.],
        [1., 1.]]) tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


* 실제로 Gradient 를 계산하면 다음과 같다.
$$o = \frac{1}{4}\sum_{i} z_{i}$$ 

$$z_{i}=3(x_{i}+2)^{2}$$

$$z_{i}|_{x_{i}=1} = 27 $$

$$ \frac{\partial o}{\partial x_{i}} = \frac{3}{2}(x_{i} + 2) $$

$$ \frac{\partial o}{\partial x_{i}}|_{x_{i}=1} = 4.5$$

### Gradients 
* out.backward()을 하면 out의 gradient를 1로 시작해 Back-propagation을 시작한다.
* .backward()를 호출한 이후부터는 .grad를 통해 각 변수의 gradient를 구할 수 있다.
* https://teamdable.github.io/techblog/PyTorch-Autograd

In [280]:
import torch

x = torch.tensor(5.0)
y = x ** 3
z = torch.log(y)

print('x', x)
print('y', y)
print('z', z)

x tensor(5.)
y tensor(125.)
z tensor(4.8283)


In [289]:
import torch

def get_tensor_info(tensor):
  info = []
  for name in ['requires_grad', 'is_leaf', 'grad_fn', 'grad']:
    info.append(f'{name}({getattr(tensor, name)})')
  info.append(f'tensor({str(tensor)})')
  return ' '.join(info)

x = torch.tensor(5.0)
y = x ** 3
z = torch.log(y)

print('x', get_tensor_info(x))
print('y', get_tensor_info(y))
print('z', get_tensor_info(z))

x requires_grad(False) is_leaf(True) grad_fn(None) grad(None) tensor(tensor(5.))
y requires_grad(False) is_leaf(True) grad_fn(None) grad(None) tensor(tensor(125.))
z requires_grad(False) is_leaf(True) grad_fn(None) grad(None) tensor(tensor(4.8283))


In [290]:
import torch

def get_tensor_info(tensor):
  info = []
  for name in ['requires_grad', 'is_leaf', 'retains_grad', 'grad_fn', 'grad']:
    info.append(f'{name}({getattr(tensor, name, None)})')
  info.append(f'tensor({str(tensor)})')
  return ' '.join(info)

x = torch.tensor(5.0, requires_grad=True)
y = x ** 3
z = torch.log(y)

print('x', get_tensor_info(x))
print('y', get_tensor_info(y))
print('z', get_tensor_info(z))

z.backward()

print('x_after_backward', get_tensor_info(x))
print('y_after_backward', get_tensor_info(y))
print('z_after_backward', get_tensor_info(z))

x requires_grad(True) is_leaf(True) retains_grad(False) grad_fn(None) grad(None) tensor(tensor(5., requires_grad=True))
y requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<PowBackward0 object at 0x7fcef0457130>) grad(None) tensor(tensor(125., grad_fn=<PowBackward0>))
z requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<LogBackward0 object at 0x7fcef03f1e20>) grad(None) tensor(tensor(4.8283, grad_fn=<LogBackward0>))
x_after_backward requires_grad(True) is_leaf(True) retains_grad(False) grad_fn(None) grad(0.6000000238418579) tensor(tensor(5., requires_grad=True))
y_after_backward requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<PowBackward0 object at 0x7fcf8f7c0fa0>) grad(None) tensor(tensor(125., grad_fn=<PowBackward0>))
z_after_backward requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<LogBackward0 object at 0x7fcef0457d00>) grad(None) tensor(tensor(4.8283, grad_fn=<LogBackward0>))


In [293]:
import torch

def get_tensor_info(tensor):
  info = []
  for name in ['requires_grad', 'is_leaf', 'retains_grad', 'grad_fn', 'grad']:
    info.append(f'{name}({getattr(tensor, name, None)})')
  info.append(f'tensor({str(tensor)})')
  return ' '.join(info)

x = torch.tensor(5.0, requires_grad=True)
y = x ** 3
z = torch.log(y)

print('x_before_backward :', get_tensor_info(x))
print('y_before_backward :', get_tensor_info(y))
print('z_before_backward :', get_tensor_info(z))

y.retain_grad()
z.retain_grad()
z.backward()

print('x_after_backward :', get_tensor_info(x))
print('y_after_backward :', get_tensor_info(y))
print('z_after_backward :', get_tensor_info(z))

x_before_backward : requires_grad(True) is_leaf(True) retains_grad(False) grad_fn(None) grad(None) tensor(tensor(5., requires_grad=True))
y_before_backward : requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<PowBackward0 object at 0x7fcef03f1880>) grad(None) tensor(tensor(125., grad_fn=<PowBackward0>))
z_before_backward : requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<LogBackward0 object at 0x7fcfc03160a0>) grad(None) tensor(tensor(4.8283, grad_fn=<LogBackward0>))
x_after_backward : requires_grad(True) is_leaf(True) retains_grad(False) grad_fn(None) grad(0.6000000238418579) tensor(tensor(5., requires_grad=True))
y_after_backward : requires_grad(True) is_leaf(False) retains_grad(True) grad_fn(<PowBackward0 object at 0x7fcf8f81f130>) grad(0.00800000037997961) tensor(tensor(125., grad_fn=<PowBackward0>))
z_after_backward : requires_grad(True) is_leaf(False) retains_grad(True) grad_fn(<LogBackward0 object at 0x7fcef03f13a0>) grad(1.0) tensor(tensor(4.8283, gr

In [292]:
import torch

def get_tensor_info(tensor):
  info = []
  for name in ['requires_grad', 'is_leaf', 'retains_grad', 'grad_fn', 'grad']:
    info.append(f'{name}({getattr(tensor, name, None)})')
  info.append(f'tensor({str(tensor)})')
  return ' '.join(info)

x = torch.tensor(5.0, requires_grad=True)
y = x ** 3
z = torch.log(y)

print('x', get_tensor_info(x))
print('y', get_tensor_info(y))
print('z', get_tensor_info(z))

z.backward()

print('x_after_backward', get_tensor_info(x))
print('y_after_backward', get_tensor_info(y))
print('z_after_backward', get_tensor_info(z))

z.backward()

x requires_grad(True) is_leaf(True) retains_grad(False) grad_fn(None) grad(None) tensor(tensor(5., requires_grad=True))
y requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<PowBackward0 object at 0x7fcef03f1970>) grad(None) tensor(tensor(125., grad_fn=<PowBackward0>))
z requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<LogBackward0 object at 0x7fcfc0316100>) grad(None) tensor(tensor(4.8283, grad_fn=<LogBackward0>))
x_after_backward requires_grad(True) is_leaf(True) retains_grad(False) grad_fn(None) grad(0.6000000238418579) tensor(tensor(5., requires_grad=True))
y_after_backward requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<PowBackward0 object at 0x7fcef03f8370>) grad(None) tensor(tensor(125., grad_fn=<PowBackward0>))
z_after_backward requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<LogBackward0 object at 0x7fcf8f7de070>) grad(None) tensor(tensor(4.8283, grad_fn=<LogBackward0>))


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [294]:

import torch

def get_tensor_info(tensor):
  info = []
  for name in ['requires_grad', 'is_leaf', 'retains_grad', 'grad_fn', 'grad']:
    info.append(f'{name}({getattr(tensor, name, None)})')
  info.append(f'tensor({str(tensor)})')
  return ' '.join(info)

x = torch.tensor(5.0, requires_grad=True)
y = x ** 3
z = torch.log(y)

print('x', get_tensor_info(x))
print('y', get_tensor_info(y))
print('z', get_tensor_info(z))

z.backward(retain_graph=True)

print('x_after_backward', get_tensor_info(x))
print('y_after_backward', get_tensor_info(y))
print('z_after_backward', get_tensor_info(z))

z.backward()

print('x_after_2backward', get_tensor_info(x))
print('y_after_2backward', get_tensor_info(y))
print('z_after_2backward', get_tensor_info(z))

x requires_grad(True) is_leaf(True) retains_grad(False) grad_fn(None) grad(None) tensor(tensor(5., requires_grad=True))
y requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<PowBackward0 object at 0x7fcef04c1be0>) grad(None) tensor(tensor(125., grad_fn=<PowBackward0>))
z requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<LogBackward0 object at 0x7fcef03f8e50>) grad(None) tensor(tensor(4.8283, grad_fn=<LogBackward0>))
x_after_backward requires_grad(True) is_leaf(True) retains_grad(False) grad_fn(None) grad(0.6000000238418579) tensor(tensor(5., requires_grad=True))
y_after_backward requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<PowBackward0 object at 0x7fcef03f8310>) grad(None) tensor(tensor(125., grad_fn=<PowBackward0>))
z_after_backward requires_grad(True) is_leaf(False) retains_grad(False) grad_fn(<LogBackward0 object at 0x7fcef04c1970>) grad(None) tensor(tensor(4.8283, grad_fn=<LogBackward0>))
x_after_2backward requires_grad(True) is_leaf(Tru